"use client";

import { buildLazyTool } from "@/components/tools/lazy-tool";
import { ToolPlaceholder } from "@/components/tools/tool-placeholder";
import type { ToolDefinition } from "@/lib/tools";

const JsonFormatterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.JsonFormatterTool));
const JsonToCsvConverterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.JsonToCsvConverterTool));
const CsvToJsonConverterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.CsvToJsonConverterTool));
const Base64EncoderTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.Base64EncoderTool));
const Base64DecoderTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.Base64DecoderTool));
const CssMinifierTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.CssMinifierTool));
const HtmlMinifierTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.HtmlMinifierTool));
const HtmlEncoderTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.HtmlEncoderTool));
const HtmlDecoderTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.HtmlDecoderTool));
const HtmlToMarkdownConverterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.HtmlToMarkdownConverterTool));
const MarkdownToHtmlConverterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.MarkdownToHtmlConverterTool));
const MarkdownEditorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.MarkdownEditorTool));
const YamlFormatterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.YamlFormatterTool));
const XmlFormatterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.XmlFormatterTool));
const JsonDiffCheckerTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.JsonDiffCheckerTool));
const CsvFormatterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.CsvFormatterTool));
const CsvViewerTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.CsvViewerTool));
const CsvDiffCheckerTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.CsvDiffCheckerTool));
const HtmlPreviewTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.HtmlPreviewTool));
const MetaTagGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.MetaTagGeneratorTool));
const KeywordDensityCheckerTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.KeywordDensityCheckerTool));
const RobotsTxtGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.RobotsTxtGeneratorTool));
const SitemapGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.SitemapGeneratorTool));
const UrlSlugGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.UrlSlugGeneratorTool));
const OpenGraphGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.OpenGraphGeneratorTool));
const UrlEncoderTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.UrlEncoderTool));
const UrlDecoderTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.UrlDecoderTool));
const UrlParserTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.UrlParserTool));
const RegexTesterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.RegexTesterTool));
const JwtDecoderTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.JwtDecoderTool));
const JwtEncoderTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.JwtEncoderTool));
const Sha256GeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.Sha256GeneratorTool));
const Md5GeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.Md5GeneratorTool));
const HashGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.HashGeneratorTool));
const BCryptGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.BCryptGeneratorTool));
const HmacGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.HmacGeneratorTool));
const SqlMinifierTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.SqlMinifierTool));
const SqlBeautifierTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.SqlBeautifierTool));
const SqlQueryFormatterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.SqlQueryFormatterTool));
const CronExpressionGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.CronExpressionGeneratorTool));
const CronExpressionParserTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.CronExpressionParserTool));
const JsonSchemaValidatorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.JsonSchemaValidatorTool));
const JsonKeyExtractorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.JsonKeyExtractorTool));
const XmlToJsonConverterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.XmlToJsonConverterTool));
const JsonToXmlConverterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.JsonToXmlConverterTool));
const RandomTokenGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.RandomTokenGeneratorTool));
const SecurePasswordStrengthCheckerTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.SecurePasswordStrengthCheckerTool));
const SecretKeyGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.SecretKeyGeneratorTool));
const EmailValidatorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.EmailValidatorTool));
const PhoneNumberFormatterTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.PhoneNumberFormatterTool));
const UUIDValidatorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.UUIDValidatorTool));
const RandomApiKeyGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.RandomApiKeyGeneratorTool));
const SecureTokenGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.SecureTokenGeneratorTool));
const PasswordEntropyCalculatorTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.PasswordEntropyCalculatorTool));
const HashIdentifierTool = buildLazyTool(() => import("@/components/tools/developer-tools").then((module) => module.HashIdentifierTool));
const FileHashCheckerTool = buildLazyTool(() => import("@/components/tools/developer-lazy-tools").then((module) => module.FileHashCheckerTool));
const FileChecksumGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-lazy-tools").then((module) => module.FileChecksumGeneratorTool));
const KeywordDifficultyCheckerPlaceholderTool = buildLazyTool(() => import("@/components/tools/developer-lazy-tools").then((module) => module.KeywordDifficultyCheckerPlaceholderTool));
const KeywordSuggestionGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-lazy-tools").then((module) => module.KeywordSuggestionGeneratorTool));
const MetaTagAnalyzerTool = buildLazyTool(() => import("@/components/tools/developer-lazy-tools").then((module) => module.MetaTagAnalyzerTool));
const PageTitleGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-lazy-tools").then((module) => module.PageTitleGeneratorTool));
const DescriptionGeneratorTool = buildLazyTool(() => import("@/components/tools/developer-lazy-tools").then((module) => module.DescriptionGeneratorTool));

export function DeveloperToolRouter({ tool }: { tool: ToolDefinition }) {
  switch (tool.slug) {
    case "json-formatter": return <JsonFormatterTool />;
    case "json-to-csv-converter": return <JsonToCsvConverterTool />;
    case "csv-to-json-converter": return <CsvToJsonConverterTool />;
    case "base64-encoder": return <Base64EncoderTool />;
    case "base64-decoder": return <Base64DecoderTool />;
    case "css-minifier": return <CssMinifierTool />;
    case "html-minifier": return <HtmlMinifierTool />;
    case "html-encoder": return <HtmlEncoderTool />;
    case "html-decoder": return <HtmlDecoderTool />;
    case "html-to-markdown-converter": return <HtmlToMarkdownConverterTool />;
    case "markdown-to-html-converter": return <MarkdownToHtmlConverterTool />;
    case "markdown-editor": return <MarkdownEditorTool />;
    case "yaml-formatter": return <YamlFormatterTool />;
    case "xml-formatter": return <XmlFormatterTool />;
    case "json-diff-checker": return <JsonDiffCheckerTool />;
    case "csv-formatter": return <CsvFormatterTool />;
    case "csv-viewer": return <CsvViewerTool />;
    case "csv-diff-checker": return <CsvDiffCheckerTool />;
    case "html-preview-tool": return <HtmlPreviewTool />;
    case "meta-tag-generator": return <MetaTagGeneratorTool />;
    case "meta-tag-analyzer": return <MetaTagAnalyzerTool />;
    case "keyword-density-checker": return <KeywordDensityCheckerTool />;
    case "keyword-difficulty-checker": return <KeywordDifficultyCheckerPlaceholderTool />;
    case "keyword-suggestion-generator": return <KeywordSuggestionGeneratorTool />;
    case "page-title-generator": return <PageTitleGeneratorTool />;
    case "description-generator": return <DescriptionGeneratorTool />;
    case "robots-txt-generator": return <RobotsTxtGeneratorTool />;
    case "sitemap-generator": return <SitemapGeneratorTool />;
    case "url-slug-generator": return <UrlSlugGeneratorTool />;
    case "open-graph-generator": return <OpenGraphGeneratorTool />;
    case "url-encoder": return <UrlEncoderTool />;
    case "url-decoder": return <UrlDecoderTool />;
    case "url-parser": return <UrlParserTool />;
    case "regex-tester": return <RegexTesterTool />;
    case "jwt-decoder": return <JwtDecoderTool />;
    case "jwt-encoder": return <JwtEncoderTool />;
    case "sha256-generator": return <Sha256GeneratorTool />;
    case "md5-generator": return <Md5GeneratorTool />;
    case "hash-generator": return <HashGeneratorTool />;
    case "bcrypt-generator": return <BCryptGeneratorTool />;
    case "hmac-generator": return <HmacGeneratorTool />;
    case "sql-minifier": return <SqlMinifierTool />;
    case "sql-beautifier": return <SqlBeautifierTool />;
    case "sql-query-formatter": return <SqlQueryFormatterTool />;
    case "cron-expression-generator": return <CronExpressionGeneratorTool />;
    case "cron-expression-parser": return <CronExpressionParserTool />;
    case "json-schema-validator": return <JsonSchemaValidatorTool />;
    case "json-key-extractor": return <JsonKeyExtractorTool />;
    case "xml-to-json-converter": return <XmlToJsonConverterTool />;
    case "json-to-xml-converter": return <JsonToXmlConverterTool />;
    case "random-token-generator": return <RandomTokenGeneratorTool />;
    case "secure-password-strength-checker": return <SecurePasswordStrengthCheckerTool />;
    case "secret-key-generator": return <SecretKeyGeneratorTool />;
    case "email-validator": return <EmailValidatorTool />;
    case "file-hash-checker": return <FileHashCheckerTool />;
    case "file-checksum-generator": return <FileChecksumGeneratorTool />;
    case "phone-number-formatter": return <PhoneNumberFormatterTool />;
    case "uuid-validator": return <UUIDValidatorTool />;
    case "random-api-key-generator": return <RandomApiKeyGeneratorTool />;
    case "secure-token-generator": return <SecureTokenGeneratorTool />;
    case "password-entropy-calculator": return <PasswordEntropyCalculatorTool />;
    case "hash-identifier": return <HashIdentifierTool />;
    default: return <ToolPlaceholder tool={tool} />;
  }
}
