"use client";

import { buildLazyTool } from "@/components/tools/lazy-tool";
import { ToolPlaceholder } from "@/components/tools/tool-placeholder";
import type { ToolDefinition } from "@/lib/tools";

const BarcodeScannerTool = buildLazyTool(() => import("@/components/tools/image-lazy-tools").then((module) => module.BarcodeScannerTool));
const QrCodeScannerTool = buildLazyTool(() => import("@/components/tools/image-lazy-tools").then((module) => module.QrCodeScannerTool));
const ColorContrastCheckerTool = buildLazyTool(() => import("@/components/tools/image-lazy-tools").then((module) => module.ColorContrastCheckerTool));
const ImageCompressorTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageCompressorTool));
const ImageFormatConverterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageFormatConverterTool));
const ImageCropperProTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageCropperProTool));
const GifMakerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.GifMakerTool));
const GifToMp4ConverterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.GifToMp4ConverterTool));
const VideoToGifConverterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.VideoToGifConverterTool));
const ImageColorPaletteGeneratorTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageColorPaletteGeneratorTool));
const ExifDataViewerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ExifDataViewerTool));
const ExifDataRemoverTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ExifDataRemoverTool));
const ImageColorInverterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageColorInverterTool));
const ImageNoiseReducerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageNoiseReducerTool));
const ImageHistogramAnalyzerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageHistogramAnalyzerTool));
const VideoMetadataViewerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.VideoMetadataViewerTool));
const VideoFrameExtractorTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.VideoFrameExtractorTool));
const VideoResolutionCheckerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.VideoResolutionCheckerTool));
const ImageMetadataViewerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageMetadataViewerTool));
const ImageDpiCheckerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageDpiCheckerTool));
const ImageBorderGeneratorTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageBorderGeneratorTool));
const ImageColorPickerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageColorPickerTool));
const BlurImageTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.BlurImageTool));
const ImageBrightnessAdjusterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageBrightnessAdjusterTool));
const ImageContrastAdjusterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageContrastAdjusterTool));
const ImageGrayscaleConverterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageGrayscaleConverterTool));
const ImageResizerTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageResizerTool));
const CropImageTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.CropImageTool));
const JpgToPngConverterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.JpgToPngConverterTool));
const PngToJpgConverterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.PngToJpgConverterTool));
const ImageToWebpConverterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageToWebpConverterTool));
const BackgroundRemoverTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.BackgroundRemoverTool));
const ImageRotatorTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageRotatorTool));
const ImageWatermarkTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageWatermarkTool));
const ImageToBase64ConverterTool = buildLazyTool(() => import("@/components/tools/image-tools").then((module) => module.ImageToBase64ConverterTool));

export function ImageToolRouter({ tool }: { tool: ToolDefinition }) {
  switch (tool.slug) {
    case "barcode-scanner": return <BarcodeScannerTool />;
    case "qr-code-scanner": return <QrCodeScannerTool />;
    case "color-contrast-checker": return <ColorContrastCheckerTool />;
    case "image-compressor": return <ImageCompressorTool />;
    case "image-format-converter": return <ImageFormatConverterTool />;
    case "image-cropper-pro": return <ImageCropperProTool />;
    case "gif-maker": return <GifMakerTool />;
    case "gif-to-mp4-converter": return <GifToMp4ConverterTool />;
    case "video-to-gif-converter": return <VideoToGifConverterTool />;
    case "image-color-palette-generator": return <ImageColorPaletteGeneratorTool />;
    case "exif-data-viewer": return <ExifDataViewerTool />;
    case "exif-data-remover": return <ExifDataRemoverTool />;
    case "image-color-inverter": return <ImageColorInverterTool />;
    case "image-noise-reducer": return <ImageNoiseReducerTool />;
    case "image-histogram-analyzer": return <ImageHistogramAnalyzerTool />;
    case "video-metadata-viewer": return <VideoMetadataViewerTool />;
    case "video-frame-extractor": return <VideoFrameExtractorTool />;
    case "video-resolution-checker": return <VideoResolutionCheckerTool />;
    case "image-metadata-viewer": return <ImageMetadataViewerTool />;
    case "image-dpi-checker": return <ImageDpiCheckerTool />;
    case "image-border-generator": return <ImageBorderGeneratorTool />;
    case "image-color-picker": return <ImageColorPickerTool />;
    case "blur-image-tool": return <BlurImageTool />;
    case "image-brightness-adjuster": return <ImageBrightnessAdjusterTool />;
    case "image-contrast-adjuster": return <ImageContrastAdjusterTool />;
    case "image-grayscale-converter": return <ImageGrayscaleConverterTool />;
    case "image-resizer": return <ImageResizerTool />;
    case "crop-image": return <CropImageTool />;
    case "jpg-to-png-converter": return <JpgToPngConverterTool />;
    case "png-to-jpg-converter": return <PngToJpgConverterTool />;
    case "image-to-webp-converter": return <ImageToWebpConverterTool />;
    case "background-remover": return <BackgroundRemoverTool />;
    case "remove-background-from-image": return <BackgroundRemoverTool />;
    case "image-rotator": return <ImageRotatorTool />;
    case "image-watermark-tool": return <ImageWatermarkTool />;
    case "image-to-base64-converter": return <ImageToBase64ConverterTool />;
    default: return <ToolPlaceholder tool={tool} />;
  }
}
