export function normalizePublicCopy(text: string): string {
  return text
    .replace(/this tool page is prepared for a future /gi, "This page includes a ")
    .replace(/this page is prepared for a future /gi, "This page includes a ")
    .replace(/this page is prepared for /gi, "This page includes ")
    .replace(/this page is structured for a future /gi, "This page includes a ")
    .replace(/the page is structured for a future /gi, "The page includes a ")
    .replace(/the page is ready for a future /gi, "The page includes a ")
    .replace(/the route and registry are ready for a future /gi, "The page includes a ")
    .replace(/the route and SEO structure ready/gi, "the page structure in place")
    .replace(/prepared for future/gi, "available")
    .replace(/prepared for a future/gi, "available for")
    .replace(/future activation/gi, "use on this site")
    .replace(/future interactive UI component/gi, "interactive tool")
    .replace(/future UI/gi, "clear tool")
    .replace(/future text area/gi, "text area")
    .replace(/future client component/gi, "tool")
    .replace(/future local implementation/gi, "tool")
    .replace(/future browser-first implementation/gi, "tool")
    .replace(/future browser-side implementation/gi, "tool")
    .replace(/future implementation/gi, "tool")
    .replace(/The future implementation can/gi, "The tool can")
    .replace(/the future implementation can/gi, "the tool can")
    .replace(/A future browser-first implementation can/gi, "The tool can")
    .replace(/A future browser-side implementation can/gi, "The tool can")
    .replace(/A future local implementation can/gi, "The tool can")
    .replace(/can later support/gi, "supports")
    .replace(/can later provide/gi, "provides")
    .replace(/can later evolve into/gi, "works as")
    .replace(/can later offer/gi, "offers")
    .replace(/can later handle/gi, "handles")
    .replace(/can later use/gi, "uses")
    .replace(/can later create/gi, "creates")
    .replace(/can later total/gi, "totals")
    .replace(/can later compare/gi, "compares")
    .replace(/can later parse/gi, "parses")
    .replace(/can later transform/gi, "transforms")
    .replace(/can later generate/gi, "generates")
    .replace(/can later support/gi, "supports")
    .replace(/later support/gi, "support")
    .replace(/later implementation/gi, "tool")
    .replace(/later when a stable local version is available/gi, "again when the feature is available on this site")
    .replace(/easy to implement later/gi, "easy to use")
    .replace(/not yet implemented/gi, "not available on this site")
    .replace(/will support/gi, "supports")
    .replace(/should support/gi, "can support")
    .replace(/should show/gi, "can show")
    .replace(/should be presented as/gi, "is best treated as")
    .replace(/should stay clear about/gi, "stays clear about")
    .replace(/intended implementation/gi, "tool")
    .replace(/intended scope/gi, "scope")
    .replace(/planned scope/gi, "scope")
    .replace(/expected behavior/gi, "normal behavior")
    .replace(/expected part of a useful future implementation/gi, "useful feature")
    .replace(/That is the expected behavior for the intended local implementation\./gi, "That is the normal behavior for this tool.")
    .replace(/That is part of the intended scope\./gi, "That is part of this tool.")
    .replace(/That is the intended design for the local implementation\./gi, "That is part of how this tool works.")
    .replace(/That should be part of the core implementation\./gi, "That is part of the tool.")
    .replace(/That is an expected part of a useful future implementation\./gi, "That is a useful feature for this tool.")
    .replace(/Coming soon because/gi, "Unavailable on this site because")
    .replace(/coming soon/gi, "currently unavailable")
    .replace(/check back soon for the full tool/gi, "use a related available tool if you need this task today")
    .replace(/browser-first workflows?/gi, "simple workflows")
    .replace(/browser-side workflows?/gi, "simple workflows")
    .replace(/browser-based workflows?/gi, "simple workflows")
    .replace(/browser-only workflows?/gi, "simple workflows")
    .replace(/browser-friendly/gi, "easy-to-use")
    .replace(/browser-first/gi, "online")
    .replace(/browser-side/gi, "online")
    .replace(/browser-based/gi, "online")
    .replace(/browser-only/gi, "online")
    .replace(/browser support/gi, "device support")
    .replace(/server-assisted workflows?/gi, "guided workflows")
    .replace(/backend-assisted workflows?/gi, "guided workflows")
    .replace(/server-assisted/gi, "guided")
    .replace(/backend-assisted/gi, "guided")
    .replace(/server-side/gi, "guided")
    .replace(/service-backed/gi, "online")
    .replace(/backend route/gi, "tool")
    .replace(/server route/gi, "tool")
    .replace(/backend/gi, "online")
    .replace(/configured service/gi, "feature")
    .replace(/current deployment/gi, "site")
    .replace(/deployment requirements/gi, "availability")
    .replace(/current implementation/gi, "tool")
    .replace(/planned implementation/gi, "tool")
    .replace(/implementation wording/gi, "details")
    .replace(/placeholder-only/gi, "preview")
    .replace(/honest placeholder/gi, "clear page")
    .replace(/placeholder text/gi, "sample text")
    .replace(/reduced-scope/gi, "limited")
    .replace(/reduced scope/gi, "limited")
    .replace(/scope note/gi, "note")
    .replace(/scope notes/gi, "notes")
    .replace(/scope boundaries/gi, "limits")
    .replace(/current architecture/gi, "site")
    .replace(/route structure/gi, "site")
    .replace(/stays honest/gi, "stays clear")
    .replace(/without external infrastructure/gi, "in a simple way")
    .replace(/browser-visible/gi, "available")
    .replace(/no-auth/gi, "no-signup")
    .replace(/cross-origin/gi, "website access")
    .replace(/CORS/gi, "website access rules")
    .replace(/\s{2,}/g, " ")
    .trim();
}

export function normalizePublicList(items: string[]): string[] {
  return items.map((item) => normalizePublicCopy(item));
}
