export type ToolCategorySlug =
  | "image-tools"
  | "pdf-tools"
  | "text-tools"
  | "developer-tools"
  | "generator-tools"
  | "calculator-tools"
  | "converter-tools"
  | "internet-tools";

export type ImplementationStatus =
  | "working-local"
  | "planned-local"
  | "reduced-scope-local"
  | "coming-soon";

export type FaqItem = {
  question: string;
  answer: string;
};

export type ToolDefinition = {
  name: string;
  slug: string;
  category: ToolCategorySlug;
  shortDescription: string;
  longDescription: string;
  keywords: string[];
  howToUse: string[];
  faq: FaqItem[];
  relatedToolSlugs: string[];
  implementationStatus: ImplementationStatus;
  seoTitle: string;
  seoDescription: string;
  statusNote?: string;
};

export type CategoryDefinition = {
  slug: ToolCategorySlug;
  name: string;
  title: string;
  description: string;
  hero: string;
};

type ToolInput = Omit<ToolDefinition, "relatedToolSlugs" | "faq"> & {
  faq1: string;
  faq2: string;
  faqAnswer1: string;
  faqAnswer2: string;
};

export const categories: CategoryDefinition[] = [
  { slug: "image-tools", name: "Image Tools", title: "Free Online Image Tools", description: "Compress, resize, crop, convert, rotate, and prepare images with browser-first workflows.", hero: "A scalable image-tools category built for future local processing components and SEO-friendly landing pages." },
  { slug: "pdf-tools", name: "PDF Tools", title: "Free Online PDF Tools", description: "Organize, convert, protect, and optimize PDFs with practical browser-side or clearly scoped workflows.", hero: "This category is structured for lightweight PDF utilities now and deeper implementations later." },
  { slug: "text-tools", name: "Text Tools", title: "Free Online Text Tools", description: "Count, format, sort, and clean text using focused utilities that are easy to extend.", hero: "Text tools fit especially well with the registry-first architecture because they are simple to add and scale." },
  { slug: "developer-tools", name: "Developer Tools", title: "Free Online Developer Tools", description: "Format, minify, encode, decode, and test common developer data directly in the browser.", hero: "The developer-tools section is ready for browser-side utilities without server infrastructure or paid APIs." },
  { slug: "generator-tools", name: "Generator Tools", title: "Free Online Generator Tools", description: "Generate passwords, QR codes, UUIDs, names, and random values from one reusable template system.", hero: "Generator tools are ideal for the shared-card and shared-metadata approach used across the site." },
  { slug: "calculator-tools", name: "Calculator Tools", title: "Free Online Calculator Tools", description: "Handle everyday finance, health, age, date, and percentage calculations with simple interfaces.", hero: "Calculator pages are organized to stay lightweight now and accept browser-side math logic later." },
  { slug: "converter-tools", name: "Converter Tools", title: "Free Online Converter Tools", description: "Convert measurements, temperatures, time values, and currencies with honest scope and clear labeling.", hero: "Converters are grouped under one scalable category so new conversion types can be added with minimal code churn." },
  { slug: "internet-tools", name: "Internet Tools", title: "Free Online Internet Tools", description: "Inspect IP and DNS-related information with transparent scope boundaries for browser-only implementations.", hero: "This category is designed to surface internet utilities without pretending the browser can do more than it really can." },
];

function makeTool(input: ToolInput): Omit<ToolDefinition, "relatedToolSlugs"> {
  return {
    name: input.name,
    slug: input.slug,
    category: input.category,
    shortDescription: input.shortDescription,
    longDescription: input.longDescription,
    keywords: input.keywords,
    howToUse: input.howToUse,
    implementationStatus: input.implementationStatus,
    seoTitle: input.seoTitle,
    seoDescription: input.seoDescription,
    statusNote: input.statusNote,
    faq: [
      { question: input.faq1, answer: input.faqAnswer1 },
      { question: input.faq2, answer: input.faqAnswer2 },
    ],
  };
}

const toolDraftsPart1: Array<Omit<ToolDefinition, "relatedToolSlugs">> = [
  makeTool({ name: "Image Compressor", slug: "image-compressor", category: "image-tools", shortDescription: "Reduce image file size with a browser-side compression workflow.", longDescription: "The Image Compressor page is structured for a local compression experience where users can upload an image, choose a quality target, preview the result, and download a smaller file. This tool is well suited to browser-side canvas-based processing and fits the current architecture cleanly.", keywords: ["image compressor", "compress image", "reduce image size"], howToUse: ["Upload an image file.", "Choose a target quality or compression level.", "Preview and download the compressed result."], implementationStatus: "planned-local", seoTitle: "Image Compressor Online", seoDescription: "Compress images online with a browser-first workflow designed for fast file-size reduction and simple downloads.", faq1: "Will this tool upload my image?", faqAnswer1: "The intended implementation is local browser-side processing so files do not need to leave the device.", faq2: "Can compressed images lose quality?", faqAnswer2: "Yes. Compression can reduce visual quality depending on the settings used." }),
  makeTool({ name: "Image Resizer", slug: "image-resizer", category: "image-tools", shortDescription: "Resize images by width and height with a simple local workflow.", longDescription: "The Image Resizer page supports a future browser-side tool that lets users change image dimensions, preserve aspect ratio, and export the result. It is a straightforward fit for the shared architecture and can plug into the registry without route changes.", keywords: ["image resizer", "resize image online", "change image size"], howToUse: ["Upload an image.", "Enter the new dimensions.", "Download the resized image."], implementationStatus: "planned-local", seoTitle: "Image Resizer Online", seoDescription: "Resize images online with a clean browser-first interface for changing width and height.", faq1: "Can I keep the aspect ratio?", faqAnswer1: "Yes. The intended local implementation should offer an aspect-ratio lock for cleaner resizing.", faq2: "Does resizing improve image quality?", faqAnswer2: "No. Resizing changes dimensions, but it does not recreate lost detail." }),
  makeTool({ name: "Crop Image", slug: "crop-image", category: "image-tools", shortDescription: "Crop an image to remove unwanted edges or focus on one area.", longDescription: "Crop Image is planned as a local image-editing utility that lets users define a crop box and export only the selected region. It works naturally with a browser canvas workflow and the site’s reusable tool template.", keywords: ["crop image", "image cropper", "trim image"], howToUse: ["Upload an image.", "Select or enter the crop area.", "Export the cropped image."], implementationStatus: "planned-local", seoTitle: "Crop Image Online", seoDescription: "Crop images online with a browser-based workflow for trimming photos and graphics.", faq1: "Will the original file be changed?", faqAnswer1: "No. The expected implementation creates a new cropped output file for download.", faq2: "Can cropping reduce file size?", faqAnswer2: "It often can, because the exported image contains fewer pixels than the original." }),
  makeTool({ name: "JPG to PNG Converter", slug: "jpg-to-png-converter", category: "image-tools", shortDescription: "Convert JPG images into PNG format locally in the browser.", longDescription: "This tool page is prepared for a local JPG to PNG conversion flow. The architecture supports a future client component that reads a JPG file, redraws it in the browser, and exports a PNG copy without server processing.", keywords: ["jpg to png", "jpeg to png", "image converter"], howToUse: ["Upload a JPG image.", "Convert the file in the browser.", "Download the PNG result."], implementationStatus: "planned-local", seoTitle: "JPG to PNG Converter Online", seoDescription: "Convert JPG to PNG online with a browser-first workflow and no unnecessary server dependency.", faq1: "Does PNG always make files smaller?", faqAnswer1: "No. PNG may be larger than JPG depending on the image content.", faq2: "Will transparency be created automatically?", faqAnswer2: "No. Converting JPG to PNG changes the file format, but it does not reconstruct missing transparency." }),
  makeTool({ name: "PNG to JPG Converter", slug: "png-to-jpg-converter", category: "image-tools", shortDescription: "Convert PNG files into JPG format with local browser-side export.", longDescription: "The PNG to JPG Converter is a strong fit for local implementation because the browser can redraw uploaded images and export them as JPG. The registry and page template are ready for that client-side conversion component.", keywords: ["png to jpg", "png to jpeg", "convert png to jpg"], howToUse: ["Upload a PNG image.", "Set JPG export options if needed.", "Download the converted JPG file."], implementationStatus: "planned-local", seoTitle: "PNG to JPG Converter Online", seoDescription: "Convert PNG to JPG online with a simple browser-side export workflow.", faq1: "What happens to transparent pixels?", faqAnswer1: "JPG does not support transparency, so transparent areas need to be flattened against a background color.", faq2: "Can JPG reduce file size?", faqAnswer2: "Often yes, especially for photographic images." }),
  makeTool({ name: "Image to WebP Converter", slug: "image-to-webp-converter", category: "image-tools", shortDescription: "Convert images to WebP for modern web-friendly compression.", longDescription: "This page is wired for a local image-to-WebP converter that would use browser-supported canvas export where available. It fits the registry model well and helps support web-optimization use cases without adding server infrastructure.", keywords: ["image to webp", "webp converter", "convert image to webp"], howToUse: ["Upload an image.", "Choose a WebP quality setting.", "Download the WebP file."], implementationStatus: "planned-local", seoTitle: "Image to WebP Converter Online", seoDescription: "Convert images to WebP online with a browser-first workflow for modern web optimization.", faq1: "Why use WebP?", faqAnswer1: "WebP can provide smaller file sizes than older formats in many cases.", faq2: "Does browser support matter?", faqAnswer2: "Yes. The local implementation depends on browser support for WebP export." }),
  makeTool({ name: "Background Remover", slug: "background-remover", category: "image-tools", shortDescription: "Planned background-removal tool with an honest coming-soon scope note.", longDescription: "Background removal is difficult to deliver well fully locally in the browser without bringing in heavy models, slow downloads, or poor UX. For that reason this page is intentionally labeled as coming soon rather than pretending a low-quality automatic cutout is production-ready.", keywords: ["background remover", "remove image background", "cut out subject"], howToUse: ["Open the page to review the planned scope.", "Check the implementation note for current limitations.", "Return later when a high-quality approach is ready."], implementationStatus: "coming-soon", seoTitle: "Background Remover Online", seoDescription: "Background remover page with an honest coming-soon scope note while the site avoids fake capability.", statusNote: "Coming soon because high-quality fully local background removal is not yet practical here without poor UX.", faq1: "Why is this marked coming soon?", faqAnswer1: "A good local background remover needs heavy segmentation logic, and shipping a poor-quality version would not meet the UX bar.", faq2: "Will you fake the feature with a weak effect?", faqAnswer2: "No. The page is intentionally honest about current feasibility." }),
  makeTool({ name: "Image Rotator", slug: "image-rotator", category: "image-tools", shortDescription: "Rotate images by common angles in a local browser workflow.", longDescription: "Image Rotator is planned as a browser-side utility for turning images by 90, 180, or 270 degrees and exporting the result. It fits neatly into the shared tool-page architecture and does not require external APIs.", keywords: ["image rotator", "rotate image", "turn photo"], howToUse: ["Upload an image.", "Choose a rotation angle.", "Download the rotated file."], implementationStatus: "planned-local", seoTitle: "Image Rotator Online", seoDescription: "Rotate images online with a simple browser-first tool for quick angle adjustments.", faq1: "Can I rotate without uploading my image?", faqAnswer1: "Yes. The intended version is designed for local browser processing.", faq2: "Will dimensions change after rotation?", faqAnswer2: "They may, depending on the angle and export format." }),
  makeTool({ name: "Image Watermark Tool", slug: "image-watermark-tool", category: "image-tools", shortDescription: "Add text or simple image watermarks before exporting a new copy.", longDescription: "The Image Watermark Tool is planned as a browser-side utility for placing text or logo overlays on uploaded images. The registry structure supports adding that interface later while the page, SEO, and related content already exist.", keywords: ["image watermark", "watermark tool", "add watermark to image"], howToUse: ["Upload an image.", "Add watermark text or a simple overlay.", "Position it and export the result."], implementationStatus: "planned-local", seoTitle: "Image Watermark Tool Online", seoDescription: "Add text or logo-style watermarks to images online with a browser-first workflow.", faq1: "Will the original be overwritten?", faqAnswer1: "No. The expected implementation would generate a new downloadable image.", faq2: "Can I use a logo watermark?", faqAnswer2: "That is the intended scope for a future local implementation." }),
  makeTool({ name: "Image to Base64 Converter", slug: "image-to-base64-converter", category: "image-tools", shortDescription: "Convert an uploaded image file into a Base64 data string.", longDescription: "This tool page is designed for a local implementation that reads an uploaded image file and outputs a Base64 string or data URL. It is a clean browser-side use case and aligns well with the registry-driven architecture.", keywords: ["image to base64", "base64 image converter", "data url converter"], howToUse: ["Upload an image file.", "Generate the Base64 output.", "Copy the encoded string or data URL."], implementationStatus: "planned-local", seoTitle: "Image to Base64 Converter Online", seoDescription: "Convert image files to Base64 online with a browser-side workflow and copy-ready output.", faq1: "Is Base64 smaller than the original file?", faqAnswer1: "No. Base64 usually increases size compared with the binary file.", faq2: "Why would I use this?", faqAnswer2: "It can be useful for embeds, quick testing, and inline data URLs." }),
  makeTool({ name: "PDF Merge", slug: "pdf-merge", category: "pdf-tools", shortDescription: "Combine multiple PDFs into a single merged document.", longDescription: "PDF Merge is planned as a browser-side utility that takes multiple PDF files and exports a single combined document. The page template is ready for that future component while keeping metadata, FAQs, and related links in place now.", keywords: ["pdf merge", "merge pdf files", "combine pdf"], howToUse: ["Upload two or more PDF files.", "Arrange the order if needed.", "Merge and download the combined PDF."], implementationStatus: "planned-local", seoTitle: "PDF Merge Online", seoDescription: "Merge PDF files online with a browser-first workflow and a clean production-ready page structure.", faq1: "Can this run without a server?", faqAnswer1: "Yes. A local browser-side merge is practical for many normal-sized PDF files.", faq2: "Do very large files have limits?", faqAnswer2: "Yes. Browser memory limits can affect larger PDF workflows." }),
  makeTool({ name: "PDF Split", slug: "pdf-split", category: "pdf-tools", shortDescription: "Split one PDF into multiple files or separate pages.", longDescription: "The PDF Split tool page is set up for a future local implementation that lets users break a PDF into single pages or selected page groups. It fits well into a browser-first architecture and can be added without changing the route structure.", keywords: ["pdf split", "split pdf pages", "separate pdf"], howToUse: ["Upload a PDF file.", "Choose the split method.", "Download the resulting PDF files."], implementationStatus: "planned-local", seoTitle: "PDF Split Online", seoDescription: "Split PDF files online with a lightweight browser-first workflow.", faq1: "Can I split by page range?", faqAnswer1: "That is the intended scope for the local implementation.", faq2: "Does splitting require an account?", faqAnswer2: "No. The site is intentionally built without auth." }),
  makeTool({ name: "PDF to Word", slug: "pdf-to-word", category: "pdf-tools", shortDescription: "Honest placeholder for a difficult local PDF-to-Word workflow.", longDescription: "A high-quality PDF-to-Word conversion tool is not practical to implement fully locally with good fidelity in this project phase. Rather than pretend otherwise, this page is labeled clearly as coming soon until a reliable approach is available.", keywords: ["pdf to word", "convert pdf to docx", "pdf to doc"], howToUse: ["Review the current scope note.", "See why the tool is not implemented yet.", "Check back when a reliable approach is ready."], implementationStatus: "coming-soon", seoTitle: "PDF to Word Converter Online", seoDescription: "PDF to Word converter page with an honest coming-soon note instead of fake or poor-quality capability.", statusNote: "Coming soon because reliable fully local PDF-to-Word conversion is not practical here without poor results.", faq1: "Why is PDF to Word not live yet?", faqAnswer1: "High-fidelity PDF-to-Word conversion is difficult to do fully locally without weak results or heavy dependencies.", faq2: "Will this page fake a conversion?", faqAnswer2: "No. The page stays honest rather than offering low-quality output." }),
  makeTool({ name: "Word to PDF", slug: "word-to-pdf", category: "pdf-tools", shortDescription: "Honest placeholder page for Word-to-PDF conversion.", longDescription: "A good fully local Word-to-PDF tool is also not practical in the current browser-only scope because parsing modern Office formats and preserving layout reliably adds complexity beyond this phase. The page is intentionally transparent about that limitation.", keywords: ["word to pdf", "docx to pdf", "convert word to pdf"], howToUse: ["Open the page to review the planned scope.", "Read the implementation note.", "Return later if a suitable local approach is added."], implementationStatus: "coming-soon", seoTitle: "Word to PDF Converter Online", seoDescription: "Word to PDF converter page with honest scope notes for a future reliable implementation.", statusNote: "Coming soon because a good fully local Word-to-PDF workflow is not practical yet in this architecture phase.", faq1: "Why is Word to PDF marked coming soon?", faqAnswer1: "Reliable browser-only Office document conversion with good formatting fidelity is not simple in this project scope.", faq2: "Could a weak version be added quickly?", faqAnswer2: "Possibly, but it would not be honest or production-ready enough for this site." }),
  makeTool({ name: "PDF Compressor", slug: "pdf-compressor", category: "pdf-tools", shortDescription: "Reduce PDF size with a clearly scoped local compression approach.", longDescription: "PDF compression is possible locally in reduced-scope ways, but true compression quality depends on the document structure. The planned version should be labeled clearly as a limited browser-side workflow rather than pretending it will optimize every PDF equally well.", keywords: ["pdf compressor", "compress pdf", "reduce pdf size"], howToUse: ["Upload a PDF file.", "Choose the available compression mode.", "Download the optimized result and compare file size."], implementationStatus: "reduced-scope-local", seoTitle: "PDF Compressor Online", seoDescription: "Compress PDF files online with clearly labeled browser-side scope and honest limitations.", statusNote: "Reduced-scope local version only; results depend heavily on the source PDF structure.", faq1: "Will every PDF compress well?", faqAnswer1: "No. Compression results vary a lot depending on how the original PDF was created.", faq2: "Why is this marked reduced-scope?", faqAnswer2: "Because a browser-only compressor can be helpful, but it cannot guarantee strong results for all PDF types." }),
  makeTool({ name: "PDF to JPG", slug: "pdf-to-jpg", category: "pdf-tools", shortDescription: "Convert PDF pages into JPG images with a local page-rendering workflow.", longDescription: "PDF to JPG is well suited to a browser-first implementation when page rendering is available. This page is ready for a future component that converts each PDF page into an image export while reusing the site’s shared tool-page structure.", keywords: ["pdf to jpg", "convert pdf to image", "pdf to jpeg"], howToUse: ["Upload a PDF file.", "Choose which pages to export.", "Download one JPG per page or the selected pages."], implementationStatus: "planned-local", seoTitle: "PDF to JPG Converter Online", seoDescription: "Convert PDF pages to JPG online with a browser-side page export workflow.", faq1: "Will each page become a separate image?", faqAnswer1: "That is the intended local workflow for this tool.", faq2: "Can image quality vary?", faqAnswer2: "Yes. Export settings and page complexity affect image output quality." }),
  makeTool({ name: "JPG to PDF", slug: "jpg-to-pdf", category: "pdf-tools", shortDescription: "Turn one or more JPG files into a PDF document.", longDescription: "JPG to PDF is a practical local tool because uploaded images can be placed into PDF pages inside the browser. The page is already prepared for that workflow and only needs the future UI component to be added.", keywords: ["jpg to pdf", "image to pdf", "convert jpg to pdf"], howToUse: ["Upload one or more JPG files.", "Arrange page order if needed.", "Create and download the PDF."], implementationStatus: "planned-local", seoTitle: "JPG to PDF Converter Online", seoDescription: "Convert JPG images to PDF online with a browser-first document builder workflow.", faq1: "Can I combine multiple images into one PDF?", faqAnswer1: "Yes. That is the intended local implementation.", faq2: "Will image dimensions affect page layout?", faqAnswer2: "Yes. The final PDF layout depends on image sizing and page-fit rules." }),
  makeTool({ name: "PDF Page Rotator", slug: "pdf-page-rotator", category: "pdf-tools", shortDescription: "Rotate selected PDF pages or the full document.", longDescription: "This page is built for a future local PDF page rotation tool. It can support rotating all pages or chosen pages while keeping the route structure, metadata, and supporting content consistent across the site.", keywords: ["pdf page rotator", "rotate pdf pages", "turn pdf pages"], howToUse: ["Upload a PDF.", "Select the pages and angle.", "Export the rotated PDF."], implementationStatus: "planned-local", seoTitle: "PDF Page Rotator Online", seoDescription: "Rotate PDF pages online with a browser-first workflow for fixing page orientation.", faq1: "Can I rotate only one page?", faqAnswer1: "That is the intended behavior for the full implementation.", faq2: "Will text remain searchable?", faqAnswer2: "In a proper PDF-page rotation workflow, yes." }),
  makeTool({ name: "PDF Page Number Adder", slug: "pdf-page-number-adder", category: "pdf-tools", shortDescription: "Add page numbers to a PDF with a future browser-side workflow.", longDescription: "This tool page is designed for a local PDF page-numbering feature where users choose number placement and export an updated file. The architecture is already prepared for it, including SEO fields and related-tool linking.", keywords: ["add page numbers to pdf", "pdf page number adder", "pdf numbering"], howToUse: ["Upload a PDF.", "Choose where the page numbers should appear.", "Apply and download the updated PDF."], implementationStatus: "planned-local", seoTitle: "PDF Page Number Adder Online", seoDescription: "Add page numbers to PDF files online with a browser-side workflow.", faq1: "Can numbering start from a custom page?", faqAnswer1: "That is an expected option for the future implementation.", faq2: "Will the original file stay unchanged?", faqAnswer2: "Yes. The tool should export a new numbered copy." }),
  makeTool({ name: "Protect PDF", slug: "protect-pdf", category: "pdf-tools", shortDescription: "Password protection is not yet available in this browser-only PDF stack.", longDescription: "Reliable PDF password protection is not practical in the current browser-only implementation without using capabilities that are outside this no-API scope. This page remains present for SEO architecture, but it stays honest instead of pretending to encrypt files.", keywords: ["protect pdf", "password protect pdf", "encrypt pdf"], howToUse: ["Open the page to review the current limitation.", "See the honest status note.", "Return later if a robust local encryption workflow becomes practical."], implementationStatus: "coming-soon", seoTitle: "Protect PDF Online", seoDescription: "Protect PDF page with an honest coming-soon note for browser-only limitations around reliable encryption.", statusNote: "Coming soon because robust PDF password protection is not practical yet with the current browser-only, no-API tool stack.", faq1: "Why is Protect PDF not live yet?", faqAnswer1: "Reliable PDF encryption is not straightforward in the current no-API browser-only stack.", faq2: "Will this page fake PDF protection?", faqAnswer2: "No. The page stays honest instead of pretending to encrypt files." }),
  makeTool({ name: "Word Counter", slug: "word-counter", category: "text-tools", shortDescription: "Count words in pasted or typed text.", longDescription: "Word Counter is a simple browser-side text utility that fits this project especially well. The page is ready for a local implementation that updates counts in real time as the user types or pastes text.", keywords: ["word counter", "count words online", "text word count"], howToUse: ["Paste or type text.", "Review the live word count.", "Adjust your content as needed."], implementationStatus: "planned-local", seoTitle: "Word Counter Online", seoDescription: "Count words online with a simple browser-based text tool.", faq1: "Does the count update live?", faqAnswer1: "That is the intended local behavior for this tool.", faq2: "Can I use it for SEO writing?", faqAnswer2: "Yes. Word counting is useful for outlines, article drafts, and content reviews." }),
  makeTool({ name: "Character Counter", slug: "character-counter", category: "text-tools", shortDescription: "Count characters with and without spaces.", longDescription: "Character Counter is well suited to a lightweight local implementation. This page is structured for a future text area that calculates total characters, characters without spaces, and other simple metrics without external services.", keywords: ["character counter", "count characters", "letter counter"], howToUse: ["Enter or paste text.", "See the total character count.", "Use the result for writing or formatting limits."], implementationStatus: "planned-local", seoTitle: "Character Counter Online", seoDescription: "Count characters online with a fast browser-first text utility.", faq1: "Can spaces be excluded?", faqAnswer1: "Yes. The intended implementation should show both totals.", faq2: "Is this helpful for social post limits?", faqAnswer2: "Yes. Character counts are often useful for captions and message limits." }),
  makeTool({ name: "Case Converter", slug: "case-converter", category: "text-tools", shortDescription: "Switch text between upper, lower, title, and sentence case.", longDescription: "Case Converter is a classic browser-side text tool and an easy fit for the site’s shared architecture. The page is ready for a local UI that transforms pasted text instantly and lets the user copy the result.", keywords: ["case converter", "uppercase lowercase", "title case converter"], howToUse: ["Paste your text.", "Choose a case style.", "Copy the converted output."], implementationStatus: "planned-local", seoTitle: "Case Converter Online", seoDescription: "Convert text case online with a browser-based uppercase, lowercase, title case, and sentence case tool.", faq1: "Will this run locally?", faqAnswer1: "Yes. Case conversion is an ideal local text utility.", faq2: "Can title case be perfect for every language?", faqAnswer2: "No. Title-casing rules vary, so the implementation should keep expectations realistic." }),
  makeTool({ name: "Remove Duplicate Lines", slug: "remove-duplicate-lines", category: "text-tools", shortDescription: "Clean a text list by removing repeated lines.", longDescription: "This tool page is prepared for a future browser-side utility that removes duplicate lines from pasted text while preserving the first occurrence. It is a clean, practical fit for the registry-driven structure.", keywords: ["remove duplicate lines", "dedupe lines", "unique line tool"], howToUse: ["Paste text with one item per line.", "Run the duplicate-removal action.", "Copy the cleaned list."], implementationStatus: "planned-local", seoTitle: "Remove Duplicate Lines Online", seoDescription: "Remove duplicate lines online with a lightweight browser-first text cleanup tool.", faq1: "Will line order be preserved?", faqAnswer1: "That is the expected behavior for the intended local implementation.", faq2: "Does this work for large lists?", faqAnswer2: "Yes, within normal browser memory limits." }),
  makeTool({ name: "Text Sorter", slug: "text-sorter", category: "text-tools", shortDescription: "Sort lines of text alphabetically in ascending or descending order.", longDescription: "Text Sorter is another strong browser-side fit. This page is ready for a local text utility that sorts line-based lists and supports simple ordering options without involving any backend.", keywords: ["text sorter", "sort text lines", "alphabetize text"], howToUse: ["Paste line-based text.", "Choose ascending or descending order.", "Copy the sorted output."], implementationStatus: "planned-local", seoTitle: "Text Sorter Online", seoDescription: "Sort lines of text online with a browser-based alphabetical sorting tool.", faq1: "Is sorting case-sensitive?", faqAnswer1: "The intended local implementation can use a case-insensitive sort for more useful default behavior.", faq2: "Can I sort numeric values?", faqAnswer2: "Yes, though plain-text sorting and numeric sorting can behave differently." }),
];
const toolDraftsPart2: Array<Omit<ToolDefinition, "relatedToolSlugs">> = [
  makeTool({ name: "JSON Formatter", slug: "json-formatter", category: "developer-tools", shortDescription: "Format and validate JSON in the browser.", longDescription: "JSON Formatter is an excellent browser-side tool that can be added later with minimal complexity. The page is already wired for SEO and related-content structure, so only the UI logic needs to be plugged in next.", keywords: ["json formatter", "json validator", "pretty print json"], howToUse: ["Paste JSON into the editor.", "Format or validate it.", "Copy the cleaned output or fix any errors."], implementationStatus: "planned-local", seoTitle: "JSON Formatter Online", seoDescription: "Format and validate JSON online with a clean browser-first developer tool.", faq1: "Can invalid JSON be corrected automatically?", faqAnswer1: "A formatter can validate input, but it should not pretend to guess broken syntax.", faq2: "Does this need a server?", faqAnswer2: "No. JSON formatting works well fully in the browser." }),
  makeTool({ name: "Base64 Encoder", slug: "base64-encoder", category: "developer-tools", shortDescription: "Encode plain text into Base64 format.", longDescription: "The Base64 Encoder page is set up for a lightweight local text utility that encodes plain text into Base64. It is a simple browser-native use case and fits the project well.", keywords: ["base64 encoder", "encode base64", "text to base64"], howToUse: ["Paste or type plain text.", "Run the encoding action.", "Copy the Base64 output."], implementationStatus: "planned-local", seoTitle: "Base64 Encoder Online", seoDescription: "Encode text to Base64 online with a simple browser-based developer tool.", faq1: "Is Base64 encryption?", faqAnswer1: "No. Base64 is encoding, not encryption.", faq2: "Can encoded output be decoded later?", faqAnswer2: "Yes. Base64 is reversible when the input is valid." }),
  makeTool({ name: "Base64 Decoder", slug: "base64-decoder", category: "developer-tools", shortDescription: "Decode Base64 strings back into readable text.", longDescription: "This page is prepared for a browser-side Base64 Decoder that takes encoded input and outputs plain text. It keeps the scope focused and honest while remaining easy to implement later.", keywords: ["base64 decoder", "decode base64", "base64 to text"], howToUse: ["Paste a Base64 string.", "Run the decoding action.", "Review and copy the decoded text."], implementationStatus: "planned-local", seoTitle: "Base64 Decoder Online", seoDescription: "Decode Base64 text online with a browser-first developer utility.", faq1: "What if the Base64 value is invalid?", faqAnswer1: "The tool should show an error rather than faking output.", faq2: "Can this decode binary files?", faqAnswer2: "The planned scope focuses on text-based decoding first." }),
  makeTool({ name: "CSS Minifier", slug: "css-minifier", category: "developer-tools", shortDescription: "Minify CSS by removing extra whitespace and comments.", longDescription: "CSS Minifier is a realistic browser-side tool as long as the implementation is clear about using a reduced-scope minification approach instead of pretending to be a full production bundler. The page is ready for that honest local version.", keywords: ["css minifier", "minify css", "compress css"], howToUse: ["Paste CSS code.", "Run the minify action.", "Copy the compact output."], implementationStatus: "reduced-scope-local", seoTitle: "CSS Minifier Online", seoDescription: "Minify CSS online with a browser-side tool and clearly labeled lightweight scope.", statusNote: "Reduced-scope local version only; useful for cleanup, not a replacement for full build-pipeline optimization.", faq1: "Will this be as advanced as a build-tool minifier?", faqAnswer1: "No. A browser-side version can be useful, but it should be labeled as a lightweight minifier.", faq2: "Can comments be removed?", faqAnswer2: "Yes. That is a typical part of CSS minification." }),
  makeTool({ name: "HTML Minifier", slug: "html-minifier", category: "developer-tools", shortDescription: "Minify HTML with a clearly scoped browser-side cleanup workflow.", longDescription: "HTML Minifier can be useful locally for trimming whitespace and basic markup cleanup, but a browser-side version should be labeled honestly as a lightweight minifier. This registry item reflects that scope clearly.", keywords: ["html minifier", "minify html", "compress html"], howToUse: ["Paste HTML markup.", "Run the minify action.", "Copy the cleaned output."], implementationStatus: "reduced-scope-local", seoTitle: "HTML Minifier Online", seoDescription: "Minify HTML online with a browser-side tool and transparent lightweight scope.", statusNote: "Reduced-scope local version only; intended for simple markup cleanup rather than full production parsing.", faq1: "Will this preserve every edge case?", faqAnswer1: "A simple local minifier may not cover every advanced markup edge case.", faq2: "Why is this reduced-scope?", faqAnswer2: "Because browser-only cleanup is useful, but it is not identical to a full production HTML optimizer." }),
  makeTool({ name: "URL Encoder", slug: "url-encoder", category: "developer-tools", shortDescription: "Encode URL components safely for links and query strings.", longDescription: "URL Encoder is a clean browser-side utility that fits naturally into this project. The page is ready for a future client component that encodes text with standard URL-safe rules.", keywords: ["url encoder", "percent encode url", "encode url component"], howToUse: ["Paste text or a URL component.", "Run the encode action.", "Copy the encoded output."], implementationStatus: "planned-local", seoTitle: "URL Encoder Online", seoDescription: "Encode URL components online with a lightweight browser-first developer tool.", faq1: "Should I encode a full URL or just parameters?", faqAnswer1: "Most often, encoding individual components is the safer approach.", faq2: "Does this require an API?", faqAnswer2: "No. URL encoding works fully in the browser." }),
  makeTool({ name: "URL Decoder", slug: "url-decoder", category: "developer-tools", shortDescription: "Decode percent-encoded URL text into readable form.", longDescription: "This page is prepared for a future browser-side URL Decoder. It will fit neatly into the shared developer-tools architecture and help users inspect query parameters and encoded strings quickly.", keywords: ["url decoder", "decode url", "percent decode"], howToUse: ["Paste encoded text.", "Run the decode action.", "Review and copy the readable result."], implementationStatus: "planned-local", seoTitle: "URL Decoder Online", seoDescription: "Decode URL-encoded text online with a browser-first developer utility.", faq1: "What if the input is malformed?", faqAnswer1: "The tool should show a clear error instead of pretending the data decoded correctly.", faq2: "Can this decode full URLs?", faqAnswer2: "Yes, as long as the encoded parts are valid." }),
  makeTool({ name: "Regex Tester", slug: "regex-tester", category: "developer-tools", shortDescription: "Test regular expressions against sample text.", longDescription: "Regex Tester is a strong fit for a browser-only implementation because JavaScript regular expressions can run directly in the page. The route and registry are ready for the future interactive UI component.", keywords: ["regex tester", "regular expression tester", "pattern matcher"], howToUse: ["Enter a regular expression.", "Add sample text.", "Review matches and errors."], implementationStatus: "planned-local", seoTitle: "Regex Tester Online", seoDescription: "Test regular expressions online with a browser-based developer tool.", faq1: "Which regex engine would be used?", faqAnswer1: "A browser-side implementation would use the JavaScript regex engine.", faq2: "Can invalid patterns be handled?", faqAnswer2: "Yes. The tool should surface syntax errors clearly." }),
  makeTool({ name: "Password Generator", slug: "password-generator", category: "generator-tools", shortDescription: "Generate strong random passwords locally in the browser.", longDescription: "Password Generator is a natural browser-side tool. The future UI can use browser randomness, configurable length, and character sets while reusing the site’s existing page template and SEO setup.", keywords: ["password generator", "random password", "secure password"], howToUse: ["Choose password options.", "Generate a new password.", "Copy the result."], implementationStatus: "planned-local", seoTitle: "Password Generator Online", seoDescription: "Generate secure passwords online with a browser-first random password tool.", faq1: "Should this use secure randomness?", faqAnswer1: "Yes. A proper implementation should use the browser’s secure random APIs.", faq2: "Can symbols be optional?", faqAnswer2: "Yes. That is a common generator setting." }),
  makeTool({ name: "QR Code Generator", slug: "qr-code-generator", category: "generator-tools", shortDescription: "Generate QR codes from text or links.", longDescription: "The QR Code Generator page is structured for a future local implementation that creates QR codes directly in the browser and allows easy download. It fits the registry architecture without requiring a remote API.", keywords: ["qr code generator", "make qr code", "generate qr code"], howToUse: ["Enter text or a URL.", "Generate the QR code.", "Download or use the image."], implementationStatus: "planned-local", seoTitle: "QR Code Generator Online", seoDescription: "Generate QR codes online with a browser-first tool for text and URL encoding.", faq1: "Can this work without an external API?", faqAnswer1: "Yes. QR generation is practical fully in the browser.", faq2: "What types of text can be encoded?", faqAnswer2: "URLs, plain text, and short structured data are common use cases." }),
  makeTool({ name: "UUID Generator", slug: "uuid-generator", category: "generator-tools", shortDescription: "Generate one or more UUIDs for development and data tasks.", longDescription: "UUID Generator is simple, useful, and fully compatible with a browser-first approach. The page is already structured for a future tool that creates copy-ready UUID lists with minimal UI complexity.", keywords: ["uuid generator", "guid generator", "random uuid"], howToUse: ["Set how many UUIDs you want.", "Generate the values.", "Copy the results."], implementationStatus: "planned-local", seoTitle: "UUID Generator Online", seoDescription: "Generate UUIDs online with a browser-based tool for development and testing workflows.", faq1: "Can this work fully locally?", faqAnswer1: "Yes. UUID generation is well suited to browser-side logic.", faq2: "Is this useful for testing?", faqAnswer2: "Yes. UUIDs are common in app development, fixtures, and examples." }),
  makeTool({ name: "Random Name Generator", slug: "random-name-generator", category: "generator-tools", shortDescription: "Generate random names from a local curated name list.", longDescription: "Random Name Generator is planned as a local tool that picks from a bundled list of names rather than pretending to use live data. That keeps the feature honest, fast, and aligned with the project’s no-database approach.", keywords: ["random name generator", "fake name generator", "name picker"], howToUse: ["Choose how many names you want.", "Generate a random list.", "Copy the names you need."], implementationStatus: "planned-local", seoTitle: "Random Name Generator Online", seoDescription: "Generate random names online with a local bundled-list approach and no database requirement.", faq1: "Will names come from a live API?", faqAnswer1: "No. A good local implementation should use a bundled curated list.", faq2: "Are these real people?", faqAnswer2: "No. The intended use is sample names, placeholders, and idea generation." }),
  makeTool({ name: "Random Number Generator", slug: "random-number-generator", category: "generator-tools", shortDescription: "Generate random numbers within a selected range.", longDescription: "Random Number Generator is a straightforward local utility that fits the site cleanly. The page is ready for a future browser-side UI with range controls, quantity settings, and duplicate options.", keywords: ["random number generator", "number picker", "rng tool"], howToUse: ["Set the minimum and maximum values.", "Choose how many numbers to generate.", "Copy the result list."], implementationStatus: "planned-local", seoTitle: "Random Number Generator Online", seoDescription: "Generate random numbers online with a browser-first range-based tool.", faq1: "Can duplicates be disabled?", faqAnswer1: "That is the intended option for the local implementation.", faq2: "Is this suitable for giveaways and draws?", faqAnswer2: "It can be useful for casual selection tasks, but high-stakes systems should use audited processes." }),
  makeTool({ name: "Age Calculator", slug: "age-calculator", category: "calculator-tools", shortDescription: "Calculate age from a birth date.", longDescription: "Age Calculator is a simple browser-side date math tool and a good match for the project’s architecture. The page is ready for a local UI that shows years, months, and days without any backend dependency.", keywords: ["age calculator", "calculate age", "date of birth calculator"], howToUse: ["Choose a birth date.", "Optionally set a comparison date.", "Review the age result."], implementationStatus: "planned-local", seoTitle: "Age Calculator Online", seoDescription: "Calculate age online with a browser-first date-based calculator.", faq1: "Can it handle leap years?", faqAnswer1: "Yes. A proper browser-side implementation can calculate with real calendar dates.", faq2: "Can I use a custom compare date?", faqAnswer2: "Yes. That is part of the intended scope." }),
  makeTool({ name: "BMI Calculator", slug: "bmi-calculator", category: "calculator-tools", shortDescription: "Calculate body mass index from height and weight.", longDescription: "BMI Calculator is well suited to a browser-only math workflow. The page is set up for a future client component that supports metric or imperial units and outputs a clear BMI score with category labels.", keywords: ["bmi calculator", "body mass index calculator", "health calculator"], howToUse: ["Enter height and weight.", "Choose the unit system if needed.", "Read the BMI score and category."], implementationStatus: "planned-local", seoTitle: "BMI Calculator Online", seoDescription: "Calculate BMI online with a simple browser-based body mass index tool.", faq1: "Is BMI medical advice?", faqAnswer1: "No. BMI is a screening metric, not a diagnosis.", faq2: "Can metric and imperial both be supported?", faqAnswer2: "Yes. That is the intended implementation scope." }),
  makeTool({ name: "Loan Calculator", slug: "loan-calculator", category: "calculator-tools", shortDescription: "Estimate monthly loan payments and total repayment.", longDescription: "Loan Calculator fits the architecture well because the core logic is simple client-side math. The future implementation can support principal, interest rate, and term inputs with immediate payment estimates.", keywords: ["loan calculator", "monthly payment calculator", "emi calculator"], howToUse: ["Enter the loan amount.", "Set the rate and term.", "Review the monthly payment and totals."], implementationStatus: "planned-local", seoTitle: "Loan Calculator Online", seoDescription: "Estimate loan payments online with a browser-first repayment calculator.", faq1: "Will this match a lender quote exactly?", faqAnswer1: "No. It should be presented as an estimate based on standard formulas.", faq2: "Does this need an API?", faqAnswer2: "No. Loan calculations are straightforward browser-side math." }),
  makeTool({ name: "Percentage Calculator", slug: "percentage-calculator", category: "calculator-tools", shortDescription: "Solve common percentage formulas quickly.", longDescription: "This page is structured for a local percentage calculator covering percent-of, increase, decrease, and related formulas. It is a simple but high-utility addition that fits the registry-based architecture well.", keywords: ["percentage calculator", "percent increase", "percent decrease"], howToUse: ["Enter the values for the formula you need.", "Review the calculated percentage result.", "Adjust inputs to compare scenarios."], implementationStatus: "planned-local", seoTitle: "Percentage Calculator Online", seoDescription: "Calculate percentages online with a browser-based percentage tool for common formulas.", faq1: "Can one page handle multiple percentage formulas?", faqAnswer1: "Yes. That is the intended design for the local implementation.", faq2: "Will results be rounded?", faqAnswer2: "Yes, typically for readability while keeping useful precision." }),
  makeTool({ name: "Date Difference Calculator", slug: "date-difference-calculator", category: "calculator-tools", shortDescription: "Find the number of days between two dates.", longDescription: "Date Difference Calculator is a practical browser-side date utility that complements the age calculator. The route and registry are ready for a future UI that shows days, weeks, months, or other useful date-gap metrics.", keywords: ["date difference calculator", "days between dates", "date duration calculator"], howToUse: ["Choose a start date.", "Choose an end date.", "Review the difference result."], implementationStatus: "planned-local", seoTitle: "Date Difference Calculator Online", seoDescription: "Calculate the difference between two dates online with a simple browser-first date tool.", faq1: "Can it show total days?", faqAnswer1: "Yes. That should be part of the core implementation.", faq2: "Will it handle time zones?", faqAnswer2: "A simple date-only version should make its assumptions clear and focus on calendar differences." }),
  makeTool({ name: "Length Converter", slug: "length-converter", category: "converter-tools", shortDescription: "Convert between common length and distance units.", longDescription: "Length Converter is a classic local unit-conversion tool. The page is ready for a browser-side UI that handles metric and imperial units while reusing the site’s shared metadata and content structure.", keywords: ["length converter", "distance converter", "meters to feet"], howToUse: ["Enter a value.", "Choose the source unit.", "Choose the target unit and read the result."], implementationStatus: "planned-local", seoTitle: "Length Converter Online", seoDescription: "Convert length units online with a browser-first distance conversion tool.", faq1: "Does this support metric and imperial units?", faqAnswer1: "Yes. That is the intended conversion scope.", faq2: "Are decimal values allowed?", faqAnswer2: "Yes. Unit converters should support fractional inputs." }),
  makeTool({ name: "Weight Converter", slug: "weight-converter", category: "converter-tools", shortDescription: "Convert between common weight and mass units.", longDescription: "Weight Converter is another straightforward browser-side utility. This page reserves a place for a local conversion component without changing the route structure later.", keywords: ["weight converter", "mass converter", "kg to lb"], howToUse: ["Enter a weight value.", "Pick the source and target units.", "Review the converted result."], implementationStatus: "planned-local", seoTitle: "Weight Converter Online", seoDescription: "Convert weight units online with a simple browser-based mass conversion tool.", faq1: "Can it convert kilograms and pounds?", faqAnswer1: "Yes. That is expected in the local implementation.", faq2: "Is this suitable for cooking and shipping estimates?", faqAnswer2: "Yes, as a general-purpose conversion tool." }),
  makeTool({ name: "Temperature Converter", slug: "temperature-converter", category: "converter-tools", shortDescription: "Convert temperatures between Celsius, Fahrenheit, and Kelvin.", longDescription: "Temperature Converter is a clean fit for local browser-side logic. The page is ready for a future client component that handles common temperature scales with immediate results.", keywords: ["temperature converter", "celsius to fahrenheit", "kelvin converter"], howToUse: ["Enter a temperature.", "Choose the from and to scales.", "Read the converted value."], implementationStatus: "planned-local", seoTitle: "Temperature Converter Online", seoDescription: "Convert temperature units online with a browser-first Celsius, Fahrenheit, and Kelvin tool.", faq1: "Can it convert negative temperatures?", faqAnswer1: "Yes. A proper local implementation should support them.", faq2: "Why is Kelvin different?", faqAnswer2: "Kelvin is an absolute scale, so negative Kelvin values are not physically valid." }),
  makeTool({ name: "Time Converter", slug: "time-converter", category: "converter-tools", shortDescription: "Convert between common time units such as seconds, minutes, and hours.", longDescription: "Time Converter is a practical unit-conversion tool that works fully locally. The route and page are ready for a future UI that handles seconds, minutes, hours, days, and other common time units.", keywords: ["time converter", "seconds to minutes", "hours to days"], howToUse: ["Enter a time value.", "Choose the original unit.", "Choose the target unit and view the result."], implementationStatus: "planned-local", seoTitle: "Time Converter Online", seoDescription: "Convert time units online with a browser-based seconds, minutes, hours, and days converter.", faq1: "Is this a timezone tool?", faqAnswer1: "No. This tool converts time units, not clock times across regions.", faq2: "Can it convert days and hours?", faqAnswer2: "Yes. That is part of the intended scope." }),
  makeTool({ name: "Currency Converter", slug: "currency-converter", category: "converter-tools", shortDescription: "Convert currencies with clearly labeled manual reference rates.", longDescription: "Live exchange rates usually require external APIs, which this project avoids. The honest local version of this tool should use clearly labeled static or manually maintained reference rates, with a visible note that values are not live market data.", keywords: ["currency converter", "exchange rate converter", "manual rates converter"], howToUse: ["Enter an amount.", "Choose the source and target currencies.", "Review the converted amount and the labeled reference rate date."], implementationStatus: "reduced-scope-local", seoTitle: "Currency Converter Online", seoDescription: "Convert currencies online with clearly labeled manual reference rates and honest scope notes.", statusNote: "Reduced-scope local version only; rates should be static or manually maintained and clearly labeled as non-live.", faq1: "Are the rates live?", faqAnswer1: "No. In this project scope the honest version should use static or manually maintained rates with clear labeling.", faq2: "Can I use this for trading decisions?", faqAnswer2: "No. Static reference rates are useful for rough estimation only." }),
  makeTool({ name: "IP Address Lookup", slug: "ip-address-lookup", category: "internet-tools", shortDescription: "Limited browser-side IP information page with honest scope boundaries.", longDescription: "A browser cannot reliably perform a full public IP lookup with rich geolocation details without external services. The honest local version of this tool should focus on limited browser-visible network information, possible local/private IP candidates, and clear labeling about what is and is not available.", keywords: ["ip address lookup", "my ip tool", "browser ip info"], howToUse: ["Open the page to review available browser-detected information.", "Check the scope note for what the browser can and cannot reveal.", "Use the limited local details only as a basic reference."], implementationStatus: "reduced-scope-local", seoTitle: "IP Address Lookup Online", seoDescription: "IP address lookup page with honest browser-side scope notes and no fake public-IP capability.", statusNote: "Reduced-scope local version only; browser-visible network info is possible, but full public-IP lookup typically needs an external service.", faq1: "Can the browser always show my public IP?", faqAnswer1: "No. A reliable public IP lookup usually depends on an external service.", faq2: "Why keep this as reduced-scope?", faqAnswer2: "Because pretending to provide full IP lookup without the needed data source would be misleading." }),
  makeTool({ name: "DNS Lookup", slug: "dns-lookup", category: "internet-tools", shortDescription: "Honest placeholder for DNS lookup beyond the current browser-only scope.", longDescription: "DNS lookups generally require server-side infrastructure or a remote resolver service that is outside the current project scope. This page is intentionally marked coming soon rather than pretending that a browser-only site can perform authoritative DNS queries on its own.", keywords: ["dns lookup", "dns checker", "domain dns records"], howToUse: ["Open the page to review the current scope.", "Read why DNS lookup is not implemented in the browser-only architecture.", "Return later if server infrastructure is added."], implementationStatus: "coming-soon", seoTitle: "DNS Lookup Online", seoDescription: "DNS lookup page with an honest coming-soon note for functionality that needs server infrastructure.", statusNote: "Coming soon because real DNS lookup needs server-side infrastructure or external resolver access beyond the current scope.", faq1: "Why is DNS Lookup not implemented yet?", faqAnswer1: "Browser-only apps do not have the low-level network access needed for real DNS record queries.", faq2: "Could this be faked with sample data?", faqAnswer2: "No. The site avoids fake capability and misleading outputs." }),
];

const toolDrafts = [...toolDraftsPart1, ...toolDraftsPart2];

const implementedToolSlugs = new Set([
  "image-compressor",
  "image-resizer",
  "crop-image",
  "jpg-to-png-converter",
  "png-to-jpg-converter",
  "image-to-webp-converter",
  "image-rotator",
  "image-watermark-tool",
  "image-to-base64-converter",
  "pdf-merge",
  "pdf-split",
  "pdf-to-jpg",
  "jpg-to-pdf",
  "pdf-page-rotator",
  "pdf-page-number-adder",
  "word-counter",
  "character-counter",
  "case-converter",
  "remove-duplicate-lines",
  "text-sorter",
  "json-formatter",
  "base64-encoder",
  "base64-decoder",
  "css-minifier",
  "html-minifier",
  "url-encoder",
  "url-decoder",
  "regex-tester",
  "password-generator",
  "qr-code-generator",
  "uuid-generator",
  "random-name-generator",
  "random-number-generator",
  "age-calculator",
  "bmi-calculator",
  "loan-calculator",
  "percentage-calculator",
  "date-difference-calculator",
  "length-converter",
  "weight-converter",
  "temperature-converter",
  "time-converter",
  "currency-converter",
  "ip-address-lookup",
]);

const implementationStatusOverrides = new Map<string, ImplementationStatus>([
  ["currency-converter", "reduced-scope-local"],
  ["ip-address-lookup", "reduced-scope-local"],
  ["pdf-compressor", "reduced-scope-local"],
  ["protect-pdf", "coming-soon"],
  ["pdf-to-word", "coming-soon"],
  ["word-to-pdf", "coming-soon"],
]);

export const tools: ToolDefinition[] = toolDrafts.map((tool) => ({
  ...tool,
  implementationStatus:
    implementationStatusOverrides.get(tool.slug) ??
    (implementedToolSlugs.has(tool.slug) ? "working-local" : tool.implementationStatus),
  relatedToolSlugs: toolDrafts
    .filter((candidate) => candidate.category === tool.category && candidate.slug !== tool.slug)
    .slice(0, 3)
    .map((candidate) => candidate.slug),
}));

export function getCategory(slug: string) {
  return categories.find((category) => category.slug === slug);
}

export function getTool(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}

export function getToolsByCategory(category: ToolCategorySlug) {
  return tools.filter((tool) => tool.category === category);
}
